---
 - name: installing iis 
   include_tasks: iis_installation.yml
 - name: creating iis_admin and enabling admin access
   include_tasks: user.yml
 - name: deploying the websites
   include_tasks: deployment.yml
